on:
  push:
    branches:    
      - master
    paths:
      - 'src/lib/**'
      - 'package.json'
  pull_request:
    branches:    
      - master
    paths:
      - 'src/lib/**'
      - 'package.json'
name: Build and Publish
jobs:
  all:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Automated releases for npm packages.
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.npm }}